language: c

before_install:
  - wget git.io/hikK5g -qO- | sudo bash
  - n stable

install:
  - npm install
  - npm run test-build

before_script:
  - sudo npm run server-setup
  - npm start &
  - sleep 5

script:
  - npm test
  - npm run test-datasource
  - npm run jshint

after_failure:
  - env
  - cat test/lib/login_data.json
  - cat node-datasource/config.js
  - sudo cat npm-debug.log
