language: node_js
node_js:
  - "0.8"
  - "0.10"

before_install:
  - wget git.io/hikK5g | sudo bash

before_script:
  - npm start &
  - sleep 5

script:
  - npm test
  - npm run test-datasource
  - npm run jshint
