language: c

before_install:
#- wget git.io/hikK5g -qO- | sudo bash
  - sudo bash node_modules/xtuple-server/bootstrap.sh
  - n stable

install:
  - npm install

before_script:
  - sudo npm run setup
  - npm start &
  - sleep 5

script:
  - npm test
  - npm run test-datasource
  - npm run jshint

after_failure:
  - env
  - sudo cat npm-debug.log
  - sudo cat bootstrap.log
