language: node_js
node_js:
  - "0.10"

before_install:
  - wget git.io/hikK5g -qO- | sudo bash

before_script:
  - sudo npm run setup
  - npm start &
  - sleep 5

script:
  - npm test
  - npm run test-datasource
  - npm run jshint
